import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const typesSource = await readFile(new URL('../src/core/types.ts', import.meta.url), 'utf8')
const apiClientSource = await readFile(new URL('../src/core/api-client.ts', import.meta.url), 'utf8')
const worksRouteSource = await readFile(new URL('../server/src/routes/works.ts', import.meta.url), 'utf8')
const dbSource = await readFile(new URL('../server/src/db.ts', import.meta.url), 'utf8')
const imageRouteSource = await readFile(new URL('../server/src/routes/image-generation.ts', import.meta.url), 'utf8')
const imagegenRouteSource = await readFile(new URL('../server/src/routes/imagegen.ts', import.meta.url), 'utf8')
const imagegenReferenceRouteSource = await readFile(new URL('../server/src/routes/imagegen-reference-assets.ts', import.meta.url), 'utf8')
const imageGenerationFailuresSource = await readFile(new URL('../server/src/services/image-generation-failures.ts', import.meta.url), 'utf8')
const imageRunnerSource = await readFile(new URL('../server/src/services/image-generation-runner.ts', import.meta.url), 'utf8')
const imagegenHistorySource = await readFile(new URL('../server/src/services/imagegen-history.ts', import.meta.url), 'utf8')
const imagegenReferenceAssetsSource = await readFile(new URL('../server/src/services/imagegen-reference-assets.ts', import.meta.url), 'utf8')
const imagegenReferenceSelectionSource = await readFile(new URL('../server/src/services/imagegen-reference-selection.ts', import.meta.url), 'utf8')
const imageConfigService = await readFile(new URL('../server/src/services/image-generation-config.ts', import.meta.url), 'utf8')
const imageProviderSource = await readFile(new URL('../server/src/services/image-providers.ts', import.meta.url), 'utf8')
const immichClientSource = await readFile(new URL('../server/src/services/immich-client.ts', import.meta.url), 'utf8')
const safeFetchSource = await readFile(new URL('../server/src/services/safe-upstream-fetch.ts', import.meta.url), 'utf8')
const serverIndexSource = await readFile(new URL('../server/src/index.ts', import.meta.url), 'utf8')
const visualStateSource = await readFile(new URL('../src/features/image-generation/visualAssetState.ts', import.meta.url), 'utf8')
const imageClientSource = await readFile(new URL('../src/features/image-generation/imageGenerationClient.ts', import.meta.url), 'utf8')
const imagegenClientSource = await readFile(new URL('../src/features/imagegen/imagegenClient.ts', import.meta.url), 'utf8')
const promptContextSource = await readFile(new URL('../src/features/image-generation/promptContext.ts', import.meta.url), 'utf8')
const promptSource = await readFile(new URL('../src/ai/prompts/imageGeneration.ts', import.meta.url), 'utf8')
const hookSource = await readFile(new URL('../src/features/image-generation/useImageGeneration.ts', import.meta.url), 'utf8')
const appSource = await readFile(new URL('../src/App.tsx', import.meta.url), 'utf8')
const sidebarSource = await readFile(new URL('../src/components/layout/Sidebar.tsx', import.meta.url), 'utf8')
const pageSource = await readFile(new URL('../src/pages/image-generation/ImageGenerationPage.tsx', import.meta.url), 'utf8')
const imagegenPageSource = await readFile(new URL('../src/pages/imagegen/ImagegenPage.tsx', import.meta.url), 'utf8')
const editorSource = await readFile(new URL('../src/features/image-generation/ImagePromptEditor.tsx', import.meta.url), 'utf8')
const selectorSource = await readFile(new URL('../src/features/image-generation/ImageModelSelector.tsx', import.meta.url), 'utf8')
const gallerySource = await readFile(new URL('../src/features/image-generation/ImageResultGallery.tsx', import.meta.url), 'utf8')
const cssSource = await readFile(new URL('../src/index.css', import.meta.url), 'utf8')
const claudeSource = await readFile(new URL('../CLAUDE.md', import.meta.url), 'utf8')
const readmeSource = await readFile(new URL('../README.md', import.meta.url), 'utf8')
const roadmapSource = await readFile(new URL('../ROADMAP.md', import.meta.url), 'utf8')

function routeBlock(source, route) {
  const start = source.indexOf(`router.post('${route}'`)
  if (start === -1) return ''
  const next = source.indexOf('\nrouter.', start + 1)
  return source.slice(start, next === -1 ? source.length : next)
}

function exportBlock(source, marker) {
  const start = source.indexOf(marker)
  if (start === -1) return ''
  const next = source.indexOf('\nexport ', start + marker.length)
  return source.slice(start, next === -1 ? source.length : next)
}

function namedFunctionBlock(source, marker, nextMarker) {
  const start = source.indexOf(marker)
  if (start === -1) return ''
  const next = source.indexOf(nextMarker, start + marker.length)
  return source.slice(start, next === -1 ? source.length : next)
}

const extractCandidatesRoute = routeBlock(imageRouteSource, '/extract-candidates')
const imagegenHistoryTypeBlock = exportBlock(typesSource, 'export interface ImagegenHistoryRecord')
const imagegenSerializeBlock = namedFunctionBlock(imagegenRouteSource, 'function serializeHistory', 'function imageVariant')
const imagegenGenerateBlock = namedFunctionBlock(imagegenPageSource, 'const handleGenerate', 'const availabilityAlert')

assert.match(typesSource, /visualAssets\?: WorkVisualAssetsConfig/, 'Work should carry optional visual asset state so old works remain loadable')
assert.match(typesSource, /ImagePromptType = 'characterFace' \| 'chapterObject' \| 'chapterClothing' \| 'chapterProp' \| 'characterFullBody'/, 'visual prompts should support split chapter clothing and prop types while keeping legacy chapterObject')
assert.match(typesSource, /ImageAssetRecord[\s\S]*storageMode: ImageStorageMode[\s\S]*immichAssetId\?: string[\s\S]*thumbnailUrl: string/, 'image asset records should store storage locators instead of upstream URLs or base64 blobs')
assert.match(typesSource, /ImageGenerationModelCapability[\s\S]*referenceImages\?: boolean[\s\S]*maxReferenceImages\?: number/, 'model capabilities should expose gated reference-image support and a max reference count')
assert.match(typesSource, /ImageViewDirection = 'front' \| 'side' \| 'back'/, 'multi-view generation should use an explicit front/side/back direction type')
assert.match(typesSource, /VisualPromptRecord[\s\S]*visualSubjectId\?: string[\s\S]*subjectLabel\?: string[\s\S]*candidateKind\?:/, 'visual prompt records should preserve candidate subject metadata so same-chapter clothing and prop prompts do not overwrite each other')
assert.match(typesSource, /VisualCandidateKind = 'character' \| 'bystander' \| 'clothing' \| 'prop'/, 'visual candidate kinds should include bystanders so non-roster chapter people can remain selectable')
assert.match(typesSource, /VisualBystanderCandidate[\s\S]*kind: 'bystander'[\s\S]*id: string[\s\S]*name: string[\s\S]*evidence\?: string/, 'bystander candidates should have an opaque id, display name, and evidence')
assert.match(typesSource, /VisualExtractedCharacter[\s\S]*alias_in_text: string\[\][\s\S]*mapping_status: 'matched' \| 'new_character'[\s\S]*matched_character: string[\s\S]*character_type: 'protagonist' \| 'supporting' \| 'unknown'[\s\S]*first_mention: string/, 'chapter visual candidates should expose rich extraction and mapping metadata')
assert.match(typesSource, /ChapterVisualCandidateResult[\s\S]*extracted_characters: VisualExtractedCharacter\[\][\s\S]*characters: VisualCharacterCandidate\[\][\s\S]*bystanders: VisualBystanderCandidate\[\][\s\S]*unmappedCharacters: string\[\]/, 'chapter visual candidates should return extracted characters and structured bystanders while preserving legacy unmapped character names')
assert.match(typesSource, /ChapterVisualCandidateResult[\s\S]*mappingStatus\?: 'ok' \| 'partial' \| 'failed'[\s\S]*mappingError\?: string/, 'chapter visual candidates should report degraded mapping without dropping extracted people')
assert.match(typesSource, /VisualCandidateCacheEntry[\s\S]*chapterContentHash: string[\s\S]*characterIndexHash: string[\s\S]*extractionVersion: string[\s\S]*result: ChapterVisualCandidateResult/, 'visual candidate cache should persist only short structured candidates plus hashes and version metadata')
assert.match(typesSource, /ImageAssetRecord[\s\S]*basePromptSnapshot\?: string[\s\S]*generationPromptSnapshot\?: string[\s\S]*viewDirection\?: ImageViewDirection[\s\S]*referenceImageIds\?: string\[\]/, 'image asset records should snapshot generated direction/reference metadata without changing saved prompt text')
assert.match(typesSource, /ImagegenHistoryStatus = ImageStorageStatus/, 'test history status should reuse image storage statuses including provider failure records')
assert.match(imagegenHistoryTypeBlock, /ownerId: string[\s\S]*prompt: string[\s\S]*generationPromptSnapshot: string[\s\S]*provider: ImageProviderType[\s\S]*providerLabel: string[\s\S]*modelId: string[\s\S]*modelName: string[\s\S]*mimeType\?: string[\s\S]*storageMode: ImageStorageMode[\s\S]*storageStatus: ImageStorageStatus[\s\S]*status: ImagegenHistoryStatus[\s\S]*localAssetId\?: string[\s\S]*immichAssetId\?: string[\s\S]*immichFilename\?: string[\s\S]*thumbnailUrl\?: string[\s\S]*originalUrl\?: string[\s\S]*referenceImageIds: string\[\][\s\S]*error\?: string[\s\S]*createdAt: number/, 'imagegen history records should expose only owner-scoped prompts, model snapshots, reference id snapshots, storage locators, status, error, and createdAt')
assert.doesNotMatch(imagegenHistoryTypeBlock, /base64|b64_json|apiKey|baseUrl|serviceUrl|Authorization|rawResponse|upstreamUrl|providerUrl|immichServiceUrl/i, 'imagegen history shared types should not expose provider credentials, upstream URLs, raw responses, or image base64')

assert.match(apiClientSource, /updateVisualAssets: \(id: string, visualAssetChanges: any\)/, 'browser client should expose a dedicated visual assets patch method')
assert.match(apiClientSource, /fetch\(`\$\{API_BASE\}\$\{url\}`[\s\S]*credentials: 'include'[\s\S]*cache: 'no-store'/, 'browser API reads should bypass cached work responses after image asset mutations')
assert.match(worksRouteSource, /router\.patch\('\/:id\/visual-assets'[\s\S]*res\.json\(\{ visualAssets: merged\.visualAssets, updatedAt \}\)/, 'visual assets should persist through a dedicated minimal endpoint')
assert.match(worksRouteSource, /mergeVisualAssets[\s\S]*prompts: mergeRecord[\s\S]*images: replaceImages \? mergeRecord\(\{\}, patch\.images\) : mergeRecord\(existing\.images, patch\.images\)/, 'visual asset patch should merge nested records while allowing explicit image replacement for deletions')
assert.match(worksRouteSource, /defaultVisualAssets[\s\S]*candidateCache: \{\}[\s\S]*mergeVisualAssets[\s\S]*candidateCache: mergeRecord\(existing\.candidateCache, patch\.candidateCache\)/, 'server visual asset merge should preserve chapter candidate cache entries')
assert.match(worksRouteSource, /'visualAssets'/, 'generic work patch allowlist should preserve visual asset state when legacy saves include it')
assert.doesNotMatch(apiClientSource, /db\.works\.update\(work\.id, \{ visualAssets:/, 'visual assets should not be sent through generic work update helpers')

assert.match(visualStateSource, /visualAssetDelta[\s\S]*changedRecordEntries/, 'visual asset persistence should compute changed record entries for prompts and images')
assert.match(visualStateSource, /candidateCache: \{\}[\s\S]*changedRecordEntries<VisualCandidateCacheEntry>\(current\.candidateCache \|\| \{\}, next\.candidateCache \|\| \{\}\)/, 'visual asset persistence should include chapter candidate cache as short structured records')
assert.doesNotMatch(visualStateSource, /chapter\.content|base64|b64_json/, 'visual asset delta helpers should not carry whole chapter content or base64 image data')
assert.match(claudeSource, /视觉资产[\s\S]*章节候选抽取和草稿生成[\s\S]*服务端读取完整章节[\s\S]*文本 AI Provider[\s\S]*浏览器请求[\s\S]*API 响应[\s\S]*视觉资产缓存/, 'project rules should document the visual-asset full-chapter exception and browser/cache/response boundary')
assert.match(readmeSource, /视觉资产流程[\s\S]*服务端读取完整章节[\s\S]*文本 AI Provider[\s\S]*浏览器请求[\s\S]*API 响应[\s\S]*作品 JSON[\s\S]*视觉资产缓存/, 'README should explain that visual assets may use full chapter text server-side without persisting it')
assert.match(roadmapSource, /章节相关提示词生成默认[\s\S]*视觉资产章节候选抽取和草稿生成是例外[\s\S]*服务端读取完整章节[\s\S]*浏览器请求[\s\S]*API 响应[\s\S]*作品 JSON/, 'roadmap constraints should preserve the default no-whole-chapter rule with a visual-asset exception')

assert.match(serverIndexSource, /app\.use\('\/api\/image-generation', requireAuth, imageGenerationRouter\)/, 'image generation routes should be mounted behind authentication')
assert.match(serverIndexSource, /import imagegenRouter from '\.\/routes\/imagegen\.js'/, 'server should load the independent imagegen test API router')
assert.match(serverIndexSource, /app\.use\('\/api\/imagegen', requireAuth, imagegenRouter\)/, 'imagegen test routes should be mounted behind authentication')
assert.equal((dbSource.match(/CREATE TABLE IF NOT EXISTS imagegenHistory/g) || []).length, 2, 'imagegen history table should be additive in both initial schema and migrateDatabase')
assert.match(dbSource, /CREATE TABLE IF NOT EXISTS imagegenHistory \([\s\S]*id TEXT PRIMARY KEY[\s\S]*ownerId TEXT NOT NULL[\s\S]*prompt TEXT NOT NULL[\s\S]*generationPromptSnapshot TEXT NOT NULL[\s\S]*provider TEXT NOT NULL[\s\S]*providerLabel TEXT NOT NULL[\s\S]*modelId TEXT NOT NULL[\s\S]*modelName TEXT NOT NULL[\s\S]*mimeType TEXT[\s\S]*storageMode TEXT NOT NULL[\s\S]*storageStatus TEXT NOT NULL[\s\S]*status TEXT NOT NULL[\s\S]*localAssetId TEXT[\s\S]*immichAssetId TEXT[\s\S]*immichFilename TEXT[\s\S]*thumbnailUrl TEXT[\s\S]*originalUrl TEXT[\s\S]*referenceImageIds TEXT[\s\S]*error TEXT[\s\S]*createdAt INTEGER NOT NULL[\s\S]*FOREIGN KEY \(ownerId\) REFERENCES users\(id\)/, 'imagegen history table should include owner, prompt, provider/model snapshots, reference id snapshot, storage locators, status, error, and createdAt')
assert.match(dbSource, /CREATE TABLE IF NOT EXISTS imagegenReferenceAssets \([\s\S]*id TEXT PRIMARY KEY[\s\S]*ownerId TEXT NOT NULL[\s\S]*mimeType TEXT NOT NULL[\s\S]*byteSize INTEGER NOT NULL[\s\S]*storageMode TEXT NOT NULL[\s\S]*storageStatus TEXT NOT NULL[\s\S]*localAssetId TEXT[\s\S]*immichAssetId TEXT[\s\S]*thumbnailUrl TEXT NOT NULL[\s\S]*originalUrl TEXT NOT NULL[\s\S]*createdAt INTEGER NOT NULL[\s\S]*FOREIGN KEY \(ownerId\) REFERENCES users\(id\)/, 'imagegen reference assets should use an additive owner-scoped table with storage locators and safe preview URLs')
assert.match(dbSource, /ALTER TABLE imagegenHistory ADD COLUMN referenceImageIds TEXT/, 'imagegen history migration should add only a nullable referenceImageIds snapshot column')
assert.match(dbSource, /CREATE TABLE IF NOT EXISTS imageGenerationFailures \([\s\S]*id TEXT PRIMARY KEY[\s\S]*surface TEXT NOT NULL CHECK \(surface IN \('work', 'imagegen'\)\)[\s\S]*ownerId TEXT NOT NULL[\s\S]*workId TEXT[\s\S]*prompt TEXT NOT NULL[\s\S]*generationPromptSnapshot TEXT NOT NULL[\s\S]*referenceImageIds TEXT[\s\S]*provider TEXT NOT NULL[\s\S]*providerLabel TEXT NOT NULL[\s\S]*modelId TEXT NOT NULL[\s\S]*modelName TEXT NOT NULL[\s\S]*storageMode TEXT NOT NULL[\s\S]*storageStatus TEXT NOT NULL CHECK \(storageStatus IN \('failed'\)\)[\s\S]*status TEXT NOT NULL CHECK \(status IN \('failed'\)\)[\s\S]*error TEXT NOT NULL[\s\S]*createdAt INTEGER NOT NULL[\s\S]*FOREIGN KEY \(ownerId\) REFERENCES users\(id\)[\s\S]*FOREIGN KEY \(workId\) REFERENCES works\(id\)/, 'shared image generation failure table should add owner/work-scoped observability fields without storing images')
assert.match(dbSource, /idx_imageGenerationFailures_ownerCreatedAt[\s\S]*idx_imageGenerationFailures_surfaceCreatedAt[\s\S]*idx_imageGenerationFailures_workCreatedAt/, 'shared image generation failure table should have owner, surface, and work indexes')
assert.match(dbSource, /export function migrateDatabase[\s\S]*CREATE TABLE IF NOT EXISTS imagegenHistory/, 'imagegen history migration should use additive CREATE TABLE IF NOT EXISTS')
assert.doesNotMatch(dbSource, /DROP TABLE|DELETE FROM works|UPDATE works SET data = '\{\}'/, 'imagegen history migration must not delete, rebuild, or rewrite existing data')
assert.match(imagegenHistorySource, /export function createImagegenHistoryRecord[\s\S]*INSERT INTO imagegenHistory \([\s\S]*ownerId[\s\S]*prompt[\s\S]*generationPromptSnapshot[\s\S]*providerLabel[\s\S]*modelId[\s\S]*modelName[\s\S]*storageStatus[\s\S]*localAssetId[\s\S]*immichAssetId[\s\S]*thumbnailUrl[\s\S]*originalUrl[\s\S]*error[\s\S]*createdAt/, 'imagegen history DAO should persist success and failure display fields')
assert.match(imagegenHistorySource, /referenceImageIds[\s\S]*JSON\.stringify\(record\.referenceImageIds\)/, 'imagegen history DAO should snapshot selected reference ids without image bytes')
assert.match(imagegenHistorySource, /export function listImagegenHistory[\s\S]*WHERE ownerId = \?[\s\S]*ORDER BY createdAt DESC/, 'imagegen history list access should always be owner-scoped')
assert.match(imagegenHistorySource, /export function getImagegenHistoryRecord[\s\S]*WHERE id = \? AND ownerId = \?/, 'imagegen history record access should require both id and ownerId')
assert.match(imagegenHistorySource, /sameOriginLocator[\s\S]*startsWith\('\/api\/'\)/, 'imagegen history locators should be same-origin API proxy paths')
assert.doesNotMatch(imagegenHistorySource, /base64|b64_json|apiKey|baseUrl|serviceUrl|Authorization|rawResponse|upstreamUrl|providerUrl|immichServiceUrl|works|visualAssets|UPDATE works SET/i, 'imagegen history DAO should not persist sensitive provider fields or touch work visual assets')
assert.match(imageRouteSource, /canUseImageGeneration[\s\S]*config\.enabled[\s\S]*features\?\.includes\('imageGeneration'\)/, 'image proxy should enforce global switch and user-level image generation grants')
assert.match(imageRouteSource, /workAccess\(request, workId, true\)/, 'image generation should require owner write access to the work')
assert.match(imageRouteSource, /resolveRunnableImageGenerationModel/, 'image generation route should delegate runnable model resolution to the shared execution layer')
assert.match(imagegenRouteSource, /router\.post\('\/generate'[\s\S]*resolveRunnableImageGenerationModel\(config, modelId\)[\s\S]*runImageGeneration\(\{/, 'imagegen test generation should resolve models and reuse the shared runner')
assert.match(imagegenRouteSource, /canUseImageGeneration[\s\S]*config\.enabled[\s\S]*features\?\.includes\('imageGeneration'\)/, 'imagegen test generation should enforce the global image switch and user grant')
assert.match(imagegenRouteSource, /ALLOWED_GENERATE_FIELDS[\s\S]*prompt[\s\S]*modelId[\s\S]*size[\s\S]*quality[\s\S]*format[\s\S]*aspectRatio[\s\S]*n[\s\S]*referenceImageIds[\s\S]*unsupportedGenerateFields/, 'imagegen test generation should accept prompt, modelId, safe model option fields, and uploaded reference asset ids only')
assert.match(imagegenRouteSource, /resolveImagegenReferenceSelection\(\{ value: body\.referenceImageIds, ownerId: request\.currentUser\.id, config, model: resolved\.model \}\)[\s\S]*referenceImages: referenceSelection\.images[\s\S]*promptSnapshot: \{ basePromptSnapshot: parsedPrompt\.prompt, generationPromptSnapshot: parsedPrompt\.prompt, referenceImageIds: referenceSelection\.ids \}/, 'imagegen test generation should resolve uploaded reference ids to server-side bytes and snapshot selected ids')
assert.match(imagegenReferenceSelectionSource, /referenceImageIds\(input\.value\)[\s\S]*validateReferenceSelection\(input\.model, parsed\.ids\)[\s\S]*Promise\.all\(parsed\.ids\.map\(id => readImagegenReferenceAsset\(input\.ownerId, id, input\.config, 'original'\)\)\)/, 'imagegen reference selection should validate ids, preserve order, and resolve current-user ProviderReferenceImage bytes')
assert.match(imagegenReferenceSelectionSource, /effectiveReferenceImageLimit[\s\S]*MAX_TEST_REFERENCE_IMAGES[\s\S]*model\.capabilities\.maxReferenceImages[\s\S]*ids\.length > limit/, 'imagegen test generation should reject unsupported models and over-cap selections before provider calls')
assert.doesNotMatch(imagegenRouteSource, /generationPromptForRequest|CHARACTER_FACE_GENERATION_SUFFIX|VIEW_DIRECTION_SUFFIX|workAccess/, 'imagegen test routes should not reuse work prompt suffixes or work access')
assert.doesNotMatch(imagegenRouteSource, /UPDATE works|visualAssets/, 'imagegen test routes should not mutate work visual assets')
assert.match(imagegenRouteSource, /router\.use\('\/reference-assets', createImagegenReferenceAssetRouter\(\{ loadImageGenerationConfig, canUseImageGeneration, safeErrorMessage \}\)\)/, 'imagegen reference uploads should mount under the independent test console API with shared feature gating')
assert.match(imagegenReferenceRouteSource, /router\.post\('\/'[\s\S]*parseReferenceUpload[\s\S]*createImagegenReferenceAsset/, 'imagegen reference uploads should be route-scoped multipart uploads stored as current-user test-console assets')
assert.match(imagegenReferenceRouteSource, /router\.get\('\/'[\s\S]*canUseImageGeneration[\s\S]*listImagegenReferenceAssets\(request\.currentUser\.id\)/, 'imagegen reference list should be feature-gated and owner-scoped')
assert.match(imagegenReferenceRouteSource, /router\.get\('\/:referenceId[\s\S]*canUseImageGeneration[\s\S]*readImagegenReferenceAsset\(request\.currentUser\.id, req\.params\.referenceId, config/, 'imagegen reference previews should be feature-gated and owner-scoped')
assert.match(imagegenReferenceRouteSource, /busboy\(\{ headers: request\.headers, limits: \{ files: 1, fields: 0, parts: 1, fileSize: MAX_IMAGE_BYTES \} \}\)[\s\S]*fieldName !== 'file'[\s\S]*validateUploadedReferenceImage/, 'imagegen reference uploads should enforce route-scoped multipart limits, a single file field, byte size, and magic-byte validation')
assert.doesNotMatch(imagegenRouteSource, /body\.(base64|b64_json|url|providerUrl|localPath|filePath|immichAssetId|localAssetId)/, 'imagegen reference uploads and generation should not trust browser-supplied raw bytes or storage locators')
assert.match(imagegenReferenceAssetsSource, /CREATE|INSERT INTO imagegenReferenceAssets[\s\S]*WHERE id = \? AND ownerId = \?/, 'imagegen reference asset DAO should create records and resolve them by both id and owner id')
assert.match(imagegenReferenceAssetsSource, /validateUploadedReferenceImage[\s\S]*detectImageMime\(buffer\)[\s\S]*image\/jpeg[\s\S]*image\/png[\s\S]*image\/webp[\s\S]*detectedMimeType !== browserMimeType/, 'imagegen reference validation should reject empty, unsupported, and spoofed uploads before persistence')
assert.match(imagegenReferenceAssetsSource, /config\.storageMode !== 'immich'[\s\S]*saveImageAsset\('imagegen', input\.ownerId[\s\S]*immichClientFromConfig\(input\.config\)[\s\S]*assertReadyForUpload\(\)[\s\S]*uploadToImmichWithRetry/, 'imagegen reference asset service should store uploads through local imagegen namespace or Immich server credentials according to storage mode')
assert.match(imagegenReferenceAssetsSource, /readImagegenReferenceAsset[\s\S]*getImagegenReferenceAsset\(ownerId, id\)[\s\S]*storageStatus !== 'succeeded'[\s\S]*readLocalImageAsset\(ownerId, localAssetId, 'imagegen'\)[\s\S]*fetchAssetBytes\(record\.immichAssetId, variant\)/, 'imagegen reference resolution should reject cross-user/unready references and resolve bytes server-side from local or Immich storage')
assert.doesNotMatch(imagegenReferenceAssetsSource, /apiKey|baseUrl|serviceUrl|Authorization|rawResponse|upstreamUrl|providerUrl|base64|b64_json|works|visualAssets|UPDATE works SET/i, 'imagegen reference asset service should not expose secrets, raw bytes, upstream URLs, or mutate work visual assets')
assert.match(imagegenRouteSource, /localScopeId: request\.currentUser\.id[\s\S]*localAssetNamespace: 'imagegen'[\s\S]*publicAssetUrl: imagegenAssetUrl/, 'imagegen test storage should use current user id and the test asset namespace instead of a work id')
assert.match(imagegenRouteSource, /function createSuccessHistoryRecord[\s\S]*createImagegenHistoryRecord\(\{[\s\S]*generationPromptSnapshot: input\.prompt[\s\S]*localAssetId: image\.localAssetId[\s\S]*immichAssetId: image\.immichAssetId[\s\S]*thumbnailUrl: image\.thumbnailUrl \|\| image\.assetUrl/, 'imagegen test generation should write success and Immich fallback storage locators to history')
assert.match(imagegenRouteSource, /catch \(error\) \{[\s\S]*createFailureHistoryRecord\(\{ \.\.\.runContext, error \}\)[\s\S]*res\.status\(502\)\.json\(serializeHistory\(record\)\)/, 'imagegen test generation should create a failed history row for provider or storage failures after model resolution')
assert.match(imagegenRouteSource, /router\.get\('\/history'[\s\S]*listImagegenHistory\(request\.currentUser\.id\)/, 'imagegen history list should be scoped to the current user')
assert.match(imagegenRouteSource, /router\.get\('\/history'[\s\S]*res\.json\(listImagegenHistory\(request\.currentUser\.id\)\.map\(serializeHistory\)\)/, 'imagegen history endpoint should return the current user history array expected by the frontend client')
assert.match(imagegenRouteSource, /router\.get\('\/assets\/:recordId'[\s\S]*getImagegenHistoryRecord\(request\.currentUser\.id, req\.params\.recordId\)[\s\S]*readLocalImageAsset\(request\.currentUser\.id, assetId, 'imagegen'\)/, 'imagegen local asset proxy should read only owner-scoped test history and test asset files')
assert.match(imagegenRouteSource, /router\.get\('\/assets\/:recordId\/:variant'[\s\S]*getImagegenHistoryRecord\(request\.currentUser\.id, req\.params\.recordId\)[\s\S]*immichClientFromConfig\(config\)[\s\S]*fetchAssetBytes\(assetId, imageVariant\(req\.params\.variant\)\)/, 'imagegen Immich asset proxy should use owner-scoped history before fetching through the backend client')
assert.doesNotMatch(imagegenSerializeBlock, /ownerId|apiKey|baseUrl|serviceUrl|Authorization|rawResponse|upstreamUrl|providerUrl|immichServiceUrl|base64|b64_json/i, 'imagegen API response serialization should not expose owner ids, upstream credentials, raw responses, or base64')
assert.match(imageRunnerSource, /resolveRunnableImageGenerationModel[\s\S]*resolveEnabledImageModel[\s\S]*生图厂商未配置 API Key/, 'shared image runner should resolve selected models through the normalized config service and reject missing provider keys')
assert.match(imageConfigService, /resolveEnabledImageModel[\s\S]*item\.enabled/, 'image generation should reject forged disabled or unknown model IDs')
assert.match(imageProviderSource, /Authorization = `Bearer \$\{apiKey\}`|Authorization: `Bearer \$\{apiKey\}`/, 'provider API keys should be injected only server-side')
assert.doesNotMatch(imageClientSource, /apiKey|baseUrl|Authorization|serviceUrl/, 'browser image generation client should not carry provider or Immich credentials or URLs')
assert.match(imageProviderSource, /response_format: 'b64_json'/, 'OpenAI-like image generation should request base64 for internal asset normalization')
assert.match(imageProviderSource, /v1\/image_generation/, 'MiniMax adapter should call the native image_generation endpoint')
assert.match(imageProviderSource, /response_format: 'base64'/, 'MiniMax adapter should request base64 output')
assert.match(imageProviderSource, /base_resp[\s\S]*image_base64[\s\S]*failed_count/, 'MiniMax adapter should parse sanitized base64 responses and partial-failure metadata')
assert.match(imageConfigService, /defaultReferenceImageCapability[\s\S]*minimax-image-generation[\s\S]*gpt-image-\[12\][\s\S]*maxReferenceImages/, 'known GPT Image and MiniMax models should default to reference-image capable config')
assert.match(imageProviderSource, /referenceImages[\s\S]*images\/edits|images\/edits[\s\S]*referenceImages/, 'OpenAI-like adapters should use the image edit path when reference images are present')
assert.match(imageProviderSource, /discoveredOpenAICapabilities[\s\S]*gpt-image-\[12\][\s\S]*referenceImages: supportsReferenceImages[\s\S]*MiniMax image-01-live[\s\S]*referenceImages: true, maxReferenceImages: 1/, 'provider discovery should mark GPT Image and MiniMax image models as reference-image capable')
assert.match(imageProviderSource, /minimaxReferenceLimit[\s\S]*model\.capabilities\.referenceImages[\s\S]*referenceImages\.length > minimaxReferenceLimit[\s\S]*subject_reference/, 'MiniMax reference-image support should follow configured model capabilities instead of a hard-coded model id')
assert.match(imageProviderSource, /subject_reference[\s\S]*type: 'character'[\s\S]*image_file/, 'MiniMax reference-image payload should use the documented character subject_reference image_file shape')
assert.match(
  imageProviderSource,
  /timeoutMs:\s*model\.requestTimeoutMs/,
  'image provider generation should pass the per-model request timeout into every safeUpstreamFetch call',
)
assert.match(imageRouteSource, /CHARACTER_FACE_GENERATION_SUFFIX[\s\S]*不要生成完整服装展示[\s\S]*手持道具[\s\S]*generationPromptForRequest[\s\S]*promptId\.split\(':'\)\[0\] === 'characterFace'[\s\S]*const generationPrompt = generationPromptForRequest\(prompt,[\s\S]*runImageGeneration\(\{[\s\S]*providerPrompt: generationPrompt[\s\S]*promptSnapshot: \{ basePromptSnapshot: prompt, generationPromptSnapshot: generationPrompt/, 'character face image generation should append a final anti-clothing/prop guard while preserving the saved prompt snapshot')
assert.doesNotMatch(imageRunnerSource, /generationPromptForRequest|CHARACTER_FACE_GENERATION_SUFFIX|VIEW_DIRECTION_SUFFIX|workAccess\(request|visualAssets|UPDATE works SET/, 'shared image runner should receive an already-final provider prompt and stay independent from work prompt rules and work persistence')
assert.match(imageRunnerSource, /WORK_ASSET_DIR = path\.join\(__dirname, '\.\.', '\.\.', 'data', 'image-assets'\)[\s\S]*IMAGEGEN_ASSET_DIR = path\.join\(__dirname, '\.\.', '\.\.', 'data', 'imagegen-assets'\)[\s\S]*localAssetNamespace\?: ImageAssetNamespace/, 'shared image runner should keep work images and imagegen test images in separate controlled server data namespaces')
assert.match(imageRunnerSource, /readLocalImageAsset\(scopeId: string, assetId: string, namespace\?: ImageAssetNamespace\)/, 'shared local asset reader should support the imagegen test asset namespace without fake work ids')
assert.match(imageRunnerSource, /assertReadyForUpload\(\)[\s\S]*generateProviderImages\(provider, model, providerPrompt/, 'Immich readiness should happen before provider generation')
assert.match(imageRunnerSource, /IMMICH_UPLOAD_RETRY_LIMIT = 3[\s\S]*uploadToImmichWithRetry/, 'Immich upload should retry three times before entering a recoverable failed state')
assert.match(imageRunnerSource, /IMMICH_THUMBNAIL_READY_ATTEMPTS[\s\S]*waitForImmichThumbnail[\s\S]*fetchAssetBytes\(assetId, 'thumbnail'\)/, 'Immich generation should wait for the storage thumbnail before returning a successful image result')
assert.match(imageRunnerSource, /uploadToImmichWithRetry\(\{ client, buffer, filename, mimeType, albumId \}\)[\s\S]*waitForImmichThumbnail\(client, uploaded\.assetId\)[\s\S]*thumbnailUrl: storage\.publicAssetUrl\(id, 'thumbnail'\)/, 'Immich success responses should be delayed until the thumbnail proxy can read the uploaded asset')
assert.match(imageRunnerSource, /storageUploadFailed[\s\S]*immichFilename/, 'provider success with Immich upload failure should return recoverable storage metadata')
assert.match(imageRouteSource, /retry-immich[\s\S]*readLocalImageAsset[\s\S]*uploadToImmichWithRetry/, 'recoverable Immich upload failures should support retrying from a local staging reference')
assert.match(imageRouteSource, /deleteLocalStagedImageAsset[\s\S]*fs\.unlinkSync[\s\S]*localAssetId: undefined/, 'successful Immich retry should delete only the matched local staging asset and clear its locator')
assert.match(immichClientSource, /async deleteAsset\(assetId: string\)[\s\S]*method: 'DELETE'[\s\S]*ids: \[assetId\][\s\S]*force: true/, 'Immich assets should be deletable through the backend client without exposing Immich credentials to the browser')
assert.match(imageRouteSource, /findImageAssetRecord[\s\S]*images\[assetId\][\s\S]*Object\.values\(images\)\.find\(image => image\.id === assetId\)/, 'image asset deletion should find records even when the map key differs from the asset id')
assert.match(imageRouteSource, /removeMatchingImageAssetRecords[\s\S]*image\.immichAssetId === deleted\.immichAssetId[\s\S]*image\.immichFilename === deleted\.immichFilename[\s\S]*image\.localAssetId === deleted\.localAssetId/, 'image asset deletion should remove duplicate stale records that point at the same storage asset')
assert.match(imageRouteSource, /router\.delete\('\/assets\/:workId\/:assetId'[\s\S]*workAccess\(request, req\.params\.workId, true\)[\s\S]*removeMatchingImageAssetRecords\(visualAssets\.images \|\| \{\}, image\)[\s\S]*UPDATE works SET updatedAt = \?, data = \? WHERE id = \?/, 'image assets should have an owner-only delete route that removes all matching records from visual assets')
assert.match(imageRouteSource, /deleteLocalImageAssetIfPresent[\s\S]*readLocalImageAsset[\s\S]*fs\.unlinkSync/, 'image asset deletion should clean only the targeted local image file when one is present')
assert.match(imageRouteSource, /buildImmichFilename[\s\S]*ownerId[\s\S]*promptTypeLabel[\s\S]*randomUUID/, 'Immich filenames should include project, user, work, prompt type and short id identifiers')
assert.match(imageRunnerSource, /detectImageMime[\s\S]*image\/png[\s\S]*image\/jpeg[\s\S]*image\/webp/, 'shared image runner should validate returned image bytes before saving')
assert.ok(
  safeFetchSource.includes('localhost') && safeFetchSource.includes('169\\.254') && safeFetchSource.includes('192\\.168'),
  'image route should reject localhost, metadata, and private-network provider targets',
)
assert.match(imageRouteSource, /router\.post\('\/providers\/discover-models'[\s\S]*currentUser\.role[\s\S]*discoverProviderModels/, 'admins should refresh provider image model candidates through a backend proxy')
assert.match(imageProviderSource, /image-01[\s\S]*image-01-live[\s\S]*source: 'preset'/, 'MiniMax discovery should use official image model presets instead of text model listing')
assert.match(imageRouteSource, /router\.get\('\/assets\/:workId\/:assetId'[\s\S]*workAccess\(request, req\.params\.workId, false\)/, 'internal image asset reads should verify access to the owning work')
assert.match(imageRouteSource, /router\.get\('\/assets\/:workId\/:assetId\/:variant'[\s\S]*workAccess\(request, req\.params\.workId, false\)[\s\S]*fetchAssetBytes/, 'Immich image reads should go through the authenticated backend proxy')
assert.match(imageRouteSource, /router\.post\('\/immich\/health'[\s\S]*currentUser\.role[\s\S]*assertReadyForUpload\(\)[\s\S]*ensureProjectAlbum\(\)/, 'admins should be able to test Immich readiness and project album setup without calling the image provider')
assert.doesNotMatch(imageRouteSource, /DROP TABLE|DELETE FROM works|rm -rf|rmSync/, 'image generation implementation must not delete data or touch destructive paths')

assert.match(promptSource, /IMAGE_PROMPT_SYSTEM_PROMPT[\s\S]*不要生成剧情正文/, 'visual prompt generation should instruct the model to return visual prompts only')
assert.match(promptSource, /buildChapterVisualCandidateInstruction[\s\S]*JSON[\s\S]*characters[\s\S]*clothing[\s\S]*props/, 'candidate extraction should use a dedicated structured instruction rather than a freeform visual prompt')
assert.match(promptSource, /characters 只列当前章节出现的人名、别名或称谓，包括主角、配角、路人、侍卫、店员、远处人群/, 'candidate extraction should ask for all visible chapter people including bystanders')
assert.match(promptSource, /characterFace[\s\S]*纯白色背景[\s\S]*大头像[\s\S]*清晰五官特征[\s\S]*眉形[\s\S]*眼睛[\s\S]*鼻梁[\s\S]*嘴唇/, 'face prompts should target reusable pure-white close-up assets with explicit facial features')
assert.match(promptSource, /主体类型是 bystander[\s\S]*只根据章节证据描述可见外貌[\s\S]*不补写姓名以外的角色生平/, 'bystander prompt drafts should use chapter evidence without inventing canonical character backstory')
assert.match(promptSource, /chapterClothing[\s\S]*纯白色背景[\s\S]*服饰主体[\s\S]*不要包含角色姓名[\s\S]*人物脸[\s\S]*身体[\s\S]*背景[\s\S]*色调[\s\S]*场景氛围/, 'clothing prompts should isolate the outfit asset and avoid character identity, body, background, tone, and scene mood')
assert.match(promptSource, /chapterProp[\s\S]*纯白色背景[\s\S]*道具主体[\s\S]*不要包含角色姓名[\s\S]*手持动作[\s\S]*背景[\s\S]*色调[\s\S]*场景氛围/, 'prop prompts should isolate the prop asset and avoid character identity, action, background, tone, and scene mood')
assert.match(promptSource, /禁止输出背景环境/, 'visual prompt instructions should reject background descriptions')
assert.match(promptSource, /整体色调/, 'visual prompt instructions should reject color-tone descriptions')
assert.match(promptSource, /场景氛围/, 'visual prompt instructions should reject scene mood descriptions')
assert.match(promptSource, /霓虹灯[\s\S]*金属墙面/, 'visual prompt instructions should reject concrete background examples')
assert.match(promptSource, /破碎感[\s\S]*禁锢感/, 'visual prompt instructions should reject emotion-heavy image-quality phrases')
assert.match(promptSource, /characterFullBody[\s\S]*白色背景[\s\S]*全身设定图/, 'full-body prompts should target white-background reusable character sheets')
assert.match(promptContextSource, /CHAPTER_EXCERPT_LIMIT = 900/, 'chapter visual prompt context should cap source excerpts')
assert.match(promptContextSource, /buildChapterExcerpt[\s\S]*paragraphs\.slice\(0, 3\)[\s\S]*slice\(0, CHAPTER_EXCERPT_LIMIT\)/, 'chapter visual prompt context should use a small excerpt rather than a whole chapter')
assert.doesNotMatch(promptContextSource, /return chapter\.content|content:\s*chapter\.content/, 'prompt context should never return whole chapter content')
assert.match(promptContextSource, /buildChapterVisualCandidateContext[\s\S]*buildChapterExcerpt[\s\S]*角色匹配索引/, 'candidate extraction context should reuse bounded excerpts and a minimized character matching index')
assert.match(promptContextSource, /ImagePromptSubjectContext[\s\S]*subjectLabel[\s\S]*subjectDescription[\s\S]*subjectEvidence[\s\S]*subjectLine/, 'prompt context should accept selected candidate subject labels, descriptions, and evidence')
assert.match(promptContextSource, /candidateKind\?: 'character' \| 'bystander' \| 'clothing' \| 'prop'/, 'prompt context should accept bystander subjects')
assert.match(promptContextSource, /candidatePersonLine[\s\S]*章节人物[\s\S]*本章未关联人物[\s\S]*character \? characterLine\(character\) : candidatePersonLine\(subject\)/, 'prompt context should describe selected bystanders instead of falling back to unselected character text')
assert.match(promptContextSource, /needsChapter = type === 'characterFace' \|\| type === 'chapterObject' \|\| type === 'chapterClothing' \|\| type === 'chapterProp'/, 'face, clothing, and prop prompts should all include bounded chapter context')
assert.match(imageRouteSource, /router\.post\('\/prompt'[\s\S]*canUseImageGeneration[\s\S]*workAccess\(request, workId, true\)/, 'visual prompt endpoint should enforce image feature permission and owner write access')
assert.match(imageRouteSource, /router\.post\('\/prompt'[\s\S]*normalizePromptType\(body\.type\)[\s\S]*buildServerImagePromptContext\(work, body\)[\s\S]*buildServerImagePromptInstruction\(type, context\)[\s\S]*IMAGE_PROMPT_SYSTEM_PROMPT/, 'visual prompt endpoint should rebuild prompt context server-side from identifiers')
assert.match(imageRouteSource, /safeVisualPromptOutput[\s\S]*hasLongSourceOverlap\(prompt, \(work\.chapters \|\| \[\]\)\.map\(fullChapterContent\)\)[\s\S]*return safeText\(prompt, 1200\)[\s\S]*res\.json\(\{ prompt: safeVisualPromptOutput\(prompt, work\) \}\)/, 'visual prompt endpoint should reject source overlap without failing ordinary overlong visual prompts')
assert.doesNotMatch(imageRouteSource, /output\.length < prompt\.trim\(\)\.length/, 'visual prompt endpoint should truncate long full-body drafts instead of returning 502')
assert.match(imageRouteSource, /characterFullBody：纯白色背景[\s\S]*只总结该角色或路人的形象[\s\S]*输出不超过 300 个汉字[\s\S]*即使输入上下文很长，也不要复述输入上下文/, 'server full-body prompt drafts should ask for a short visual summary instead of expanding long context')
assert.match(imageRouteSource, /chapterClothing：纯白色背景[\s\S]*只总结该角色或路人的服饰形象[\s\S]*上下文是“无描述”[\s\S]*不要扩写章节正文/, 'server clothing drafts should keep no-description bystander clothing short instead of expanding chapter context')
assert.match(imageRouteSource, /serverReferenceImageLines[\s\S]*normalizeReferenceImageIds\(body\.referenceImageIds\)[\s\S]*work\.visualAssets\?\.images[\s\S]*work\.visualAssets\?\.prompts[\s\S]*promptType === 'characterFullBody'[\s\S]*已选参考图/, 'server prompt context should rebuild selected reference summaries from stored visual assets and exclude full-body references')
assert.match(imageRouteSource, /referenceUsageLine[\s\S]*type === 'characterFace'[\s\S]*面部和身份以参考图\$\{index\}为准[\s\S]*type === 'chapterClothing'[\s\S]*穿着参考图\$\{index\}所示的服装[\s\S]*type === 'chapterProp'[\s\S]*拿着或佩戴/, 'server prompt instructions should map face, clothing, and prop references to different full-body draft guidance')
assert.match(imageRouteSource, /characterFullBody 如果没有参考图[\s\S]*完整描述面部识别点[\s\S]*characterFullBody 如果上下文包含参考图[\s\S]*头像参考图只写[\s\S]*服饰参考图只写[\s\S]*道具参考图根据正文/, 'full-body draft instruction should describe complete details only when no references are selected')
assert.match(promptSource, /characterFullBody：纯白色背景[\s\S]*只总结该角色或路人的形象[\s\S]*输出不超过 300 个汉字[\s\S]*即使输入上下文很长，也不要复述输入上下文/, 'shared prompt instruction should keep full-body drafts short if reused')
assert.match(promptSource, /chapterClothing：纯白色背景[\s\S]*只总结该角色或路人的服饰形象[\s\S]*上下文是“无描述”[\s\S]*不要扩写章节正文/, 'shared prompt instruction should keep no-description bystander clothing drafts short if reused')
assert.doesNotMatch(imageRouteSource, /body\.systemPrompt|body\.instruction|body\.context/, 'visual prompt endpoint should not trust browser-submitted systemPrompt, instruction, or context')
assert.match(imageRouteSource, /router\.post\('\/extract-candidates'[\s\S]*canUseImageGeneration[\s\S]*workAccess\(request, workId, true\)/, 'candidate extraction endpoint should enforce image feature permission and owner write access')
assert.match(imageRouteSource, /extract-candidates[\s\S]*chapterId[\s\S]*buildChapterVisualCandidateContext[\s\S]*buildPeopleExtractionInstruction[\s\S]*buildPeopleMappingInstruction/, 'candidate extraction should accept workId and chapterId only, then rebuild full chapter context and split extraction from mapping server-side')
assert.doesNotMatch(extractCandidatesRoute, /body\.context|body\.chapterContent|rawAiResponse|stack|apiKey|baseUrl/, 'candidate extraction responses should not trust browser context or leak raw AI output')
assert.match(imageRouteSource, /buildPeopleExtractionInstruction[\s\S]*小说完整章节[\s\S]*不做作品角色映射[\s\S]*extracted_characters[\s\S]*mapping_status[\s\S]*matched_character[\s\S]*first_mention/, 'server candidate extraction prompt should extract full-chapter people before role mapping')
assert.match(imageRouteSource, /buildPeopleExtractionInstruction[\s\S]*不要尝试把人物映射到作品角色库[\s\S]*服务端会提供完整章节正文/, 'server extraction prompt should explicitly allow full chapter input while forbidding mapping in the extraction step')
assert.match(imageRouteSource, /buildPeopleMappingInstruction[\s\S]*章节抽取人物[\s\S]*作品已知人物列表[\s\S]*matched_character_id[\s\S]*matched_character_name[\s\S]*confidence/, 'server mapping prompt should map extracted people to canonical work characters in a second step')
assert.match(imageRouteSource, /buildPropsExtractionInstruction[\s\S]*小说章节道具抽取助手[\s\S]*不要提取人物[\s\S]*不要生成视觉提示词[\s\S]*"props"/, 'server should extract chapter props with a dedicated prop-only prompt')
assert.match(imageRouteSource, /buildClothingExtractionInstruction[\s\S]*小说章节服饰抽取助手[\s\S]*章节人物列表[\s\S]*"clothing"[\s\S]*只记录章节明文服饰[\s\S]*固定“无描述”选项/, 'server should extract clothing with a dedicated explicit-clothing prompt and leave no-description to the UI')
assert.match(imageRouteSource, /parseCandidateJSON[\s\S]*extracted_characters: Array\.isArray\(parsed\.extracted_characters\)[\s\S]*chapter_summary/, 'candidate parser should accept the richer extracted_characters response shape')
assert.match(imageRouteSource, /parseCharacterMappingJSON[\s\S]*mappings: Array\.isArray\(parsed\.mappings\)/, 'mapping parser should accept a separate mapping response shape')
assert.match(imageRouteSource, /createHash[\s\S]*candidateId\(kind: 'bystander' \| 'clothing' \| 'prop'[\s\S]*digest\('hex'\)[\s\S]*slice\(0, 8\)/, 'candidate ids should use opaque hashes rather than raw evidence text')
assert.match(imageRouteSource, /function mapCharacterName[\s\S]*candidateKeys[\s\S]*exactMatches\.length === 1[\s\S]*containsMatches\.length === 1/, 'character matching should accept only unique normalized exact or containment matches')
assert.match(imageRouteSource, /normalizeExtractedCharacters[\s\S]*response\.extracted_characters[\s\S]*response\.characters/, 'candidate mapping should preserve backward compatibility with old characters responses')
assert.match(imageRouteSource, /findMappingMatch[\s\S]*matched_character_id[\s\S]*matched_character_name[\s\S]*const extracted_characters[\s\S]*mapping_status: matched \? 'matched'[\s\S]*unmappedCharacters: bystanders\.map[\s\S]*mappingStatus: mappingError \? 'partial'/, 'candidate mapping should validate AI mappings and preserve unmapped people as structured bystander candidates')
assert.match(imageRouteSource, /findMappingMatch\(item, name, aliases\)[\s\S]*subjectOwnerByName[\s\S]*registerSubjectOwner[\s\S]*mapSubjects[\s\S]*subjectOwnerByName\.get\(normalizeCandidateKey\(item\.characterName\)\)/, 'clothing and prop subject mapping should reuse extracted-person role mapping instead of rematching by raw names only')
assert.match(imageRouteSource, /mappingError = '角色映射失败，已保留未关联人物候选。'[\s\S]*mapCandidateResponse\(work, candidates, mapping, mappingError\)/, 'mapping failures should degrade to unmapped candidates instead of failing the whole extraction')
assert.doesNotMatch(imageRouteSource, /inferredClothing|根据身份\/场景推断|基础服饰[\s\S]*\.\.\.inferredClothing/, 'candidate mapping should not add automatic inferred clothing fallbacks')
assert.match(imageRouteSource, /Promise\.all\(\[[\s\S]*buildPropsExtractionInstruction\(context\)[\s\S]*buildClothingExtractionInstruction\(context, extracted\)[\s\S]*const candidates = \{ \.\.\.extraction, props: props\.props, clothing: clothing\.clothing \}/, 'candidate route should merge independently extracted props and clothing into the chapter candidate result')
assert.match(imageRouteSource, /generateTextPrompt[\s\S]*loadSystemAIConfig[\s\S]*chat\/completions/, 'visual prompt endpoint should use text AI config rather than image provider config')
assert.match(imageRouteSource, /catch \{[\s\S]*视觉提示词生成失败，请稍后重试/, 'visual prompt errors should be sanitized before reaching the browser')
assert.match(imageClientSource, /ImagePromptRequest[\s\S]*type: ImagePromptType[\s\S]*characterId\?: string[\s\S]*chapterId\?: string[\s\S]*visualSubjectId\?: string[\s\S]*candidateKind\?: VisualCandidateKind[\s\S]*referenceImageIds\?: string\[\][\s\S]*prompt: \(payload: ImagePromptRequest\)/, 'browser image client should call the visual prompt endpoint with identifiers and selected reference image ids only')
assert.doesNotMatch(imageClientSource, /systemPrompt|instruction|context:/, 'browser image client should not send freeform prompt context fields')
assert.match(imageClientSource, /extractCandidates: \(payload: ImageCandidateRequest\)/, 'browser image client should call a dedicated chapter candidate extraction endpoint')
assert.match(imageClientSource, /referenceImageIds\?: string\[\][\s\S]*viewDirection\?: ImageViewDirection/, 'browser image generation request should carry reference image ids and one-shot view direction')
assert.doesNotMatch(
  imageClientSource,
  /requestTimeoutMs|timeoutMs/,
  'browser image generation request should not carry a per-model request timeout so admins stay in control of the backend timeout',
)
assert.match(imageClientSource, /deleteAsset: \(payload: ImageDeleteRequest\)[\s\S]*method: 'DELETE'/, 'browser image client should expose an internal image asset delete request')
assert.match(hookSource, /interface PromptDraftInput[\s\S]*referenceImageIds\?: string\[\][\s\S]*generatePromptDraft = async \(\{ type, characterId, chapterId, subject, referenceImageIds \}: PromptDraftInput\)[\s\S]*imageGenerationClient\.prompt\(\{ workId: currentWork\.id, type, characterId, chapterId, visualSubjectId: subject\?\.visualSubjectId, candidateKind: subject\?\.candidateKind, referenceImageIds \}\)/, 'image generation hook should request prompt drafts with typed identifiers and selected references only')
assert.doesNotMatch(hookSource, /buildImagePromptContext|buildImagePromptInstruction|IMAGE_PROMPT_SYSTEM_PROMPT/, 'image generation hook should not build visual prompt context in the browser')
assert.match(hookSource, /promptId[\s\S]*visualSubjectId \|\| 'none'|visualSubjectId \|\| 'none'[\s\S]*join\(':'\)/, 'prompt ids should include candidate subject identity to avoid same-chapter prompt collisions')
assert.match(hookSource, /CANDIDATE_EXTRACTION_VERSION[\s\S]*candidateCacheMetadata[\s\S]*chapterContentHash[\s\S]*characterIndexHash/, 'candidate cache should be invalidated by chapter content, character index, and extraction version')
assert.match(hookSource, /validCandidateCache[\s\S]*entry\.status === 'success'[\s\S]*extractChapterCandidates[\s\S]*options: \{ refresh\?: boolean \}[\s\S]*!options\.refresh[\s\S]*validCandidateCache\(cached, metadata\)[\s\S]*imageGenerationClient\.extractCandidates/, 'image generation hook should reuse valid cached chapter candidates unless refresh is requested')
assert.match(hookSource, /draftPrompt[\s\S]*status: 'draft'/, 'generated visual prompts should start as editable drafts instead of auto-saving final prompts')
assert.match(hookSource, /status: 'imageFailed'[\s\S]*error:/, 'image generation failures should preserve the prompt record with retryable error state')
assert.match(hookSource, /const deleteImage = async \(image: ImageAssetRecord\)[\s\S]*imageGenerationClient\.deleteAsset[\s\S]*setCurrentWork\(\{ \.\.\.work, visualAssets: result\.visualAssets, updatedAt: result\.updatedAt \}\)/, 'image asset deletion should refresh visual asset state from the server response instead of relying on merge patches')
assert.doesNotMatch(hookSource, /prompt: `[^`]*(正面|侧面|背面)|prompt:\s*record\.prompt\s*\+/, 'frontend should not mutate saved prompt text with one-shot view direction')

assert.match(appSource, /path="\/image-generation"/, 'app routing should include the visual assets workspace')
assert.match(appSource, /path="\/imagegen"[\s\S]*<ImagegenPage \/>/, 'app routing should expose the independent imagegen test console inside the protected workspace')
assert.match(sidebarSource, /canOpenImageGeneration[\s\S]*key: '\/image-generation'[\s\S]*label: '视觉资产'/, 'sidebar should expose visual assets only when a work is open and view/generation is allowed')
assert.match(sidebarSource, /canOpenImagegen = imageGenerationEnabled && canUseFeature\(user, permissionSources, 'imageGeneration'\)[\s\S]*key: '\/imagegen'[\s\S]*label: '生图测试'/, 'sidebar should expose the imagegen test console from the global switch and imageGeneration permission without a work requirement')
assert.doesNotMatch(sidebarSource, /canOpenImagegen = hasWork|canOpenImagegen = Boolean\(currentWork/, 'imagegen sidebar visibility should not depend on an open work')
assert.match(sidebarSource, /import\s*\{\s*canUseFeature\s*\}\s*from\s*['"]@\/core\/feature-permissions['"][\s\S]*novelImportConfig\s*=\s*useSystemConfigStore\([\s\S]*\.novelImportConfig[\s\S]*imageGenerationEnabled\s*=\s*useSystemConfigStore\([\s\S]*\.imageGenerationConfig\.enabled[\s\S]*permissionSources\s*:\s*FeaturePermissionSources\s*=\s*\{[\s\S]*novelImportConfig[\s\S]*imageGenerationConfig\s*:\s*\{\s*enabled\s*:\s*imageGenerationEnabled\s*\}[\s\S]*canUseFeature\(user, permissionSources, 'importBackfill'\)[\s\S]*canUseFeature\(user, permissionSources, 'imageGeneration'\)/, 'sidebar should subscribe to permission config snapshots so switch and grant saves immediately refresh feature visibility')
assert.doesNotMatch(sidebarSource, /useSystemConfigStore\(\(s\) => s\.canUseFeature\)/, 'sidebar should not rely on the stable store permission action for reactive feature visibility')
assert.match(pageSource, /视觉资产工作台[\s\S]*readOnly[\s\S]*当前账号未授权生图/, 'visual workspace should distinguish read-only and unauthorized execution states')
assert.match(pageSource, /PROMPT_TYPES[\s\S]*characterFace[\s\S]*chapterClothing[\s\S]*chapterProp[\s\S]*characterFullBody/, 'visual workspace should expose split chapter clothing and prop prompt types')
assert.match(pageSource, /typeRequiresChapter[\s\S]*characterFace[\s\S]*chapterClothing[\s\S]*chapterProp[\s\S]*characterFullBody[\s\S]*missingRequiredChapter[\s\S]*请先选择章节/, 'face, clothing, prop, and full-body actions should be disabled until a chapter is selected')
assert.match(pageSource, /ImagePromptEditor[\s\S]*ImageModelSelector[\s\S]*ImageResultGallery[\s\S]*retryImmichUpload/, 'visual workspace should connect prompt editing, model selection, result gallery, and Immich retry')
assert.match(imagegenPageSource, /ImageModelSelector[\s\S]*ImageResultGallery[\s\S]*imagegenClient\.history/, 'imagegen console should reuse model selection and result gallery while loading test history from its own API client')
assert.match(imagegenPageSource, /failedHistory[\s\S]*record\.status === 'failed'[\s\S]*测试生成失败[\s\S]*record\.generationPromptSnapshot/, 'imagegen console should show failed test history records even when no image URL can be displayed')
assert.match(imagegenPageSource, /displayableGalleryImages[\s\S]*image\.thumbnailUrl \|\| image\.originalUrl \|\| image\.assetUrl[\s\S]*<ImageResultGallery images=\{displayableGalleryImages\}/, 'imagegen console should pass only records with image URLs into the image gallery')
assert.match(imagegenPageSource, /imagegenClient\.generate\(\{[\s\S]*prompt,[\s\S]*modelId/, 'imagegen console should submit the user prompt and selected model to the test API')
assert.doesNotMatch(imagegenPageSource, /<Input(?=[\s>])[^>]*type="file"/, 'imagegen reference upload should use a native file input so selecting a file cannot crash Ant Design Input during rerender')
assert.match(imagegenPageSource, /<input[\s\S]*type="file"[\s\S]*accept="image\/png,image\/jpeg,image\/webp"/, 'imagegen reference upload should keep the native file input constrained to supported image formats')
assert.doesNotMatch(imagegenPageSource, /currentWork|visualAssets/, 'imagegen console should not read or mutate work visual assets')
assert.doesNotMatch(imagegenGenerateBlock, /workId|chapterId|promptId|characterId|visualSubjectId|viewDirection|systemPrompt|instruction|context/, 'imagegen console generate requests should exclude work-context fields')
assert.match(imagegenClientSource, /fetch\(`\/api\/imagegen\$\{url\}`[\s\S]*credentials: 'include'/, 'imagegen client should call the same-origin test API with credentials')
assert.match(imagegenClientSource, /generate: \(payload: ImagegenGenerateRequest\)[\s\S]*request<ImagegenHistoryResponse>\('\/generate'/, 'imagegen client should generate through the dedicated test endpoint')
assert.match(imagegenClientSource, /history: \(\) => request<ImagegenHistoryResponse\[\]>\('\/history'/, 'imagegen client should load only imagegen test history')
assert.match(imagegenClientSource, /referenceImageIds\?: readonly string\[\][\s\S]*uploadReferenceAsset[\s\S]*FormData\(\)[\s\S]*formData\.append\('file', file\)/, 'imagegen client should support uploaded reference ids and FormData uploads without raw context fields')
assert.doesNotMatch(imagegenClientSource, /workId|chapterId|promptId|characterId|visualSubjectId|viewDirection|systemPrompt|instruction|context/, 'imagegen client request types should exclude work-context fields')
assert.match(pageSource, /handleDeleteImage[\s\S]*deleteImage\(image\)[\s\S]*setReferenceImageIds\(current => current\.filter\(id => id !== image\.id\)\)[\s\S]*onDelete=\{handleDeleteImage\}/, 'visual workspace should delete image assets and remove deleted assets from selected references')
assert.match(pageSource, /useEffect\([\s\S]*invalidSelectedReferenceIds\.length[\s\S]*setReferenceImageIds\(current => current\.filter\(id => eligibleReferenceIds\.has\(id\)\)\)[\s\S]*eligibleReferenceIds, invalidSelectedReferenceIds\.length/, 'reference image selection should drop ids that are no longer eligible after asset deletion or refresh')
assert.match(visualStateSource, /hasRemovedImages[\s\S]*Object\.keys\(current\.images\)\.some[\s\S]*_replaceImages: true/, 'visual asset delta should explicitly request full image replacement when image records are removed')
assert.match(visualStateSource, /hasRemovedImages \|\| Object\.keys\(images\)\.length \? \{ images \} : \{\}/, 'visual asset delta should send an empty images object when the last image record is removed')
assert.match(worksRouteSource, /replaceImages = patch\._replaceImages === true[\s\S]*images: replaceImages \? mergeRecord\(\{\}, patch\.images\) : mergeRecord\(existing\.images, patch\.images\)/, 'visual asset persistence should replace images when the client delta represents deletions')
assert.match(pageSource, /CandidateState[\s\S]*extractChapterCandidates\(nextChapterId, \{ refresh \}\)[\s\S]*handleChapterChange[\s\S]*setCandidateState\(nextChapterId \? \{ chapterId: nextChapterId, status: 'idle' \}/, 'chapter changes should hide stale candidates before loading, while loadChapterCandidates can reuse cache')
assert.match(pageSource, /promptId\(type: ImagePromptType, characterId\?: string, chapterId\?: string, visualSubjectId\?: string\)[\s\S]*visualSubjectId \|\| 'none'/, 'page prompt ids should match the hook subject-aware prompt id shape')
assert.match(pageSource, /legacyPromptId[\s\S]*!selectedPromptSubjectId \? visualAssets\.prompts\[selectedLegacyPromptId\]/, 'legacy prompt records without subject metadata should still show when no subject is selected')
assert.match(pageSource, /typeUsesChapterCharacters[\s\S]*characterFace[\s\S]*chapterClothing[\s\S]*characterFullBody[\s\S]*selectedCharacterId/, 'face, clothing, and full-body flows should use chapter-mapped character options')
assert.match(pageSource, /characterOptions[\s\S]*label: `作品角色 \/ \$\{candidate\.name\}`[\s\S]*label: `本章未关联人物 \/ \$\{candidate\.name\}`/, 'chapter character dropdown labels should show only person identity without clothing, prop, or evidence snippets')
assert.match(pageSource, /BYSTANDER_OPTION_PREFIX[\s\S]*candidateBystanders[\s\S]*本章未关联人物/, 'chapter character dropdown should include structured bystander candidates')
assert.match(pageSource, /type === 'chapterClothing'[\s\S]*selectedCharacterId[\s\S]*candidate\.characterId === selectedCharacterId[\s\S]*selectedBystander[\s\S]*candidate\.characterCandidateId === selectedBystander\.id/, 'chapter clothing candidates should be scoped to either selected mapped characters or selected bystanders')
assert.match(pageSource, /NO_DESCRIPTION_CLOTHING_ID[\s\S]*label: '无描述'[\s\S]*description: '当前章节未提供明确服饰描述[\s\S]*\[NO_DESCRIPTION_CLOTHING_OPTION, \.\.\.candidateState\.result\.clothing\.filter/, 'chapter clothing should always include a fixed no-description option above AI clothing candidates')
assert.match(pageSource, /candidateResultHasCharacter[\s\S]*candidateResultHasSubject[\s\S]*if \(refresh\)[\s\S]*setCharacterId\(undefined\)[\s\S]*setVisualSubjectId\(undefined\)[\s\S]*handleRefreshCandidates[\s\S]*loadChapterCandidates\(chapterId, true\)/, 'refreshing chapter candidates should update all AI dropdown data and clear stale selections')
assert.match(pageSource, /type === 'chapterProp'[\s\S]*return candidateState\.result\.props/, 'chapter prop candidates should come directly from chapter props without a character selection')
assert.match(pageSource, /type !== 'chapterProp'[\s\S]*选择本章映射角色|type !== 'chapterProp'[\s\S]*选择本章人物/, 'chapter prop flow should not show the character selector')
assert.match(pageSource, /unmappedClothingCandidates[\s\S]*!candidate\.characterId && !candidate\.characterCandidateId[\s\S]*未关联服饰/, 'unmapped clothing should be shown separately instead of mixed into a selected character or bystander dropdown')
assert.match(pageSource, /typeUsesCandidateSubject[\s\S]*missingRequiredSubject[\s\S]*draftSubject = selectedSubject[\s\S]*subjectDescription: selectedSubject\.description[\s\S]*subjectEvidence: selectedSubject\.evidence[\s\S]*generatePromptDraft\(\{ type, characterId: selectedCharacterId, chapterId, subject: draftSubject/, 'chapter clothing and prop drafts should require and pass selected subject metadata')
assert.match(pageSource, /selectedBystander[\s\S]*candidateKind: 'bystander'[\s\S]*generatePromptDraft\(\{ type, characterId: selectedCharacterId, chapterId, subject: draftSubject/, 'bystander selections should pass candidate-only subject context into prompt draft generation')
assert.match(pageSource, /promptDrafts[\s\S]*hasUnsavedPromptEdit[\s\S]*confirmPromptOverwrite/, 'visual workspace should preserve prompt edits per prompt id and confirm before overwriting hand edits')
assert.match(pageSource, /style=\{\{ width: '100%' \}\}/, 'visual workspace selects should fill the filter panel width for mobile')
assert.match(pageSource, /VIEW_DIRECTION_OPTIONS[\s\S]*front[\s\S]*side[\s\S]*back[\s\S]*Segmented<ImageViewDirection>/, 'full-body generation should expose a keyboard-accessible direction segmented control')
assert.match(pageSource, /referenceImageIds[\s\S]*maxReferenceImages[\s\S]*当前模型不支持参考图[\s\S]*generateImage\(recordForActions, effectiveModelId, \{ referenceImageIds, viewDirection \}\)/, 'full-body generation should gate selected references by model support and pass refs plus one-shot direction without mutating prompt text')
assert.match(pageSource, /Object\.values\(visualAssets\.images\)[\s\S]*status === 'succeeded'[\s\S]*storageStatus === 'succeeded'[\s\S]*getImageAssetDisplayUrl[\s\S]*item\.prompt\?\.type !== 'characterFullBody'/, 'reference image picker should use only succeeded non-full-body images with display URLs')
assert.match(pageSource, /characterNameById[\s\S]*currentWork\?\.characters[\s\S]*prompt\?\.subjectLabel \|\| characterName \|\| prompt\?\.title \|\| image\.promptSnapshot\.slice\(0, 18\) \|\| '已生成图片'/, 'reference image labels should prefer candidate subject labels, then canonical character names, then prompt titles and snapshots')
assert.match(pageSource, /generatePromptDraft\(\{ type, characterId: selectedCharacterId, chapterId, subject: draftSubject, referenceImageIds: type === 'characterFullBody' \? referenceImageIds : undefined \}\)/, 'full-body draft generation should include selected reference ids so the draft can avoid duplicating referenced details')
assert.match(editorSource, /生成草稿[\s\S]*保存提示词[\s\S]*复制[\s\S]*生成图片/, 'prompt editor should expose draft, save, copy, and image generation actions')
assert.match(selectorSource, /style=\{\{ width: '100%' \}\}[\s\S]*capabilities\.sizes[\s\S]*capabilities\.qualities[\s\S]*capabilities\.formats/, 'model selector should fill the panel width and surface model capability summaries')
assert.match(selectorSource, /capabilities\.referenceImages[\s\S]*maxReferenceImages[\s\S]*参考图/, 'model selector should surface reference-image support and max count')
assert.match(gallerySource, /const visibleImages = images\.filter\(image => getImageAssetDisplayUrl\(image\) && !loadFailures\[image\.id\]\)[\s\S]*visibleImages\.map/, 'gallery should hide assets without a loadable thumbnail display URL')
assert.match(gallerySource, /const displayUrl = getImageAssetDisplayUrl\(image\)[\s\S]*Image src=\{displayUrl\}/, 'gallery should render storage-agnostic backend thumbnail proxy URLs')
assert.match(gallerySource, /const originalUrl = getImageAssetDisplayUrl\(image, 'original'\)[\s\S]*preview=\{originalUrl \? \{ src: originalUrl \} : false\}/, 'gallery previews should open the original image URL instead of reusing the thumbnail URL')
assert.match(gallerySource, /generationPromptSnapshot[\s\S]*实际调用提示词|实际调用提示词[\s\S]*generationPromptSnapshot/, 'gallery should show the final provider prompt snapshot when an image records it')
assert.match(gallerySource, /copyProviderPrompt[\s\S]*generationPromptSnapshot[\s\S]*message\.success\('已复制实际调用提示词'\)/, 'gallery should expose a copy action for the final provider prompt')
assert.match(gallerySource, /Popconfirm[\s\S]*删除这张图片资产[\s\S]*onConfirm=\{\(\) => onDelete\?\.\(image\)\}/, 'gallery should expose a confirmed delete action for editable image assets')
assert.match(gallerySource, /onError[\s\S]*setLoadFailures/, 'gallery should hide thumbnail load failures after the image reports an error')
assert.match(cssSource, /image-generation-layout[\s\S]*@media \(max-width: 768px\)[\s\S]*grid-template-columns: 1fr/, 'visual workspace should collapse into a single-column mobile layout')
assert.match(cssSource, /image-reference-grid[\s\S]*minmax\(128px, 1fr\)[\s\S]*@media \(max-width: 768px\)[\s\S]*image-reference-grid[\s\S]*minmax\(112px, 1fr\)/, 'reference image grid should remain readable in desktop and mobile single-column flows')

console.log('image-generation behavior assertions passed')
